name: GSM Master Branch CI

# Trigger the workflow on push to "master" or pull request targeting "master"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17 for the project
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  # Enable Gradle dependency caching

      # Grant execute permissions to the Gradle wrapper script
      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x gradlew

      # Run the unit tests
      - name: Run Unit Tests
        run: ./gradlew test
